# Generated by Django 4.1.7 on 2024-04-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
