# Generated by Django 4.1.7 on 2024-04-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo',
        ),
    ]
